version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd standard-core
      - yarn install
  build:
    commands:
      - yarn build-storybook
artifacts:
  files:
    - "**/*"
  base-directory: standard-core/storybook-static
  discard-paths: no
